### ISSUE TITLE
Another homonym issue

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#102]
http://bie.ala.org.au/search?q=Scoparia
 
1. Duplicate NZOR entries for the same name – why?
2. http://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2909378 has a moth image but this image does not appear in the gallery. JSON results from bie-index (http://bie.ala.org.au/ws/species/http://id.biodiversity.org.au/node/apni/2909378.json) show that record has imageIdentifier: "75cf4b29-c85c-48fa-b7ae-44051ecb7787" – but looking at preferred images list, that GUID is not found? So I’m not sure how that imageID is getting in there?

**Comment by charvolant** [comment]
1. Is easy. One is an animal the other is a plant. It looks like the image search needs some work to ensure that kingdom is correct. It should search first on taxonID and then on name. For Scoparia there is only one image, so it looks like the secondary name search is finding the Moth by name.
2. Looks like the same problem, where we've ended up with a selected image of a moth for something that is a plant. This will go into the preferred image id and the UI is tacking it onto the end.

I'll try a fix where kingdom is also a required match.

**Comment by nickdos** [comment]
Related issue is that there are 4 entries returned - 2 for plant and 2 for animals and it seems the NZOR entries should **not** be there as there are already APINI and AFD entries present.

**Comment by charvolant** [comment]
For the NZOR duplicates, we have:

1. APNI Scoparia L. http://id.biodiversity.org.au/node/apni/2909378 which has a family of Plantaginaceae Juss. (APNI) and a kingdom of Plantae 
2. NZOR Scoparia NZOR-3-65937 which has a family of Scrophulariaceae Juss. (APNI, correctly matched from the NZOR taxon) and a kingdom of Plantae 
3. NZOR Scoparia NZOR-3-118653 which has a subfamily of SCOPARIINAE (AFD, correctly matched from the NZOR taxon) and a kingdom of Animalia

Scoparia L. http://id.biodiversity.org.au/node/apni/2909378 and Scoparia Haworth, 1811 both appear in the APNI and AFI lists. This creates a matching problem during processing the NZOR names and leads to the NZOR names being erroneously included, since a single APNI/AFD match isn't found.

The Talend OS processing of NZOR needs to be fixed to disambiguate homonyms based on kingdom. This means including an extra layer of iterative processing in the Talend OS jobs. Blurgh. Oh well, per ardua ad astra

**Comment by charvolant** [comment]
As part of the fixes to https://github.com/AtlasOfLivingAustralia/bie-index/issues/118 NZOR-3-65937 is now matched to http://id.biodiversity.org.au/node/apni/2909378 and NZOR-3-118653 to urn:lsid:biodiversity.org.au:afd.taxon:86c464ee-ce25-402b-9a2c-cd8bb4df7f9f

These will be corrected during the next full build of the name index.
