### ISSUE TITLE
Occurrence records being indexed against "unplaced" version of name

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#119]
The name _Daviesia pubigera_, returns 2 exact matches, one with an 'accepted' taxonomicStatus and one with 'unplaced'.

The occurrence records are being matched against the unplaced version "http://id.biodiversity.org.au/name/apni/247314" instead of the accepted version "http://id.biodiversity.org.au/node/apni/2908174".

http://biocache.ala.org.au/occurrences/search?q=lsid:http://id.biodiversity.org.au/name/apni/247314 179 results.

http://biocache.ala.org.au/occurrences/search?q=lsid:http://id.biodiversity.org.au/node/apni/2908174 0 results.

**Comment by ryonen** [comment]
I've just noticed in APC that the accepted name Daviesia pubigera A.Cunn. ex Benth. has an isonym - Daviesia pubigera A.Cunn. ex Benth., published two years later. An isonym is the same name, based on the same type, but published elsewhere, and most commonly be a different author. In this case it has the same author, which makes it more confusing... In any case the name published in 1837 is the one that should be being retrieved rather than the 1839 name.

**Comment by charvolant** [comment]
Generally, the accepted taxon should be chosen in the case of ambiguity. This can be done by impoving the name matching library. See https://github.com/AtlasOfLivingAustralia/ala-name-matching/issues/27

**Comment by johnbaums** [comment]
_Eucalyptus largiflorens_ provides another example: [unplaced](http://bie.ala.org.au/species/http://id.biodiversity.org.au/name/apni/237885) (7339 records) vs. [accepted](http://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2887153) (3 records).

**Comment by charvolant** [comment]
Just checked Eucalyptus largiflorens. The new name index that is being tested has only one instance, with the invalid name removed. 
Also checked Daviesia pubigera. Isonym removed.

**Comment by adam-collins** [comment]
Comment says this is no longer an issue.
