### ISSUE TITLE
ws/download service fails with URL-encoded ":"

### ISSUE THREAD

**Issue by raymondben** [AtlasOfLivingAustralia/bie-index#127]
This fails, but used to work:
http://bie.ala.org.au/ws/download?q=rk_family%3ASPHENISCIDAE

But this works:
http://bie.ala.org.au/ws/download?q=rk_family:SPHENISCIDAE

Special characters in the query string should be URL-encoded, so most (all?) web libraries making requests will do it. The associated function in ALA4R is currently failing because it is URL-encoding.

**Comment by nickdos** [comment]
Hi Ben - sorry I missed this the first time. 

We were forced to add a quick fix to the BIE last week after a Linux security update was run on that server. The update included a tomcat security fix which changed the way our instance of SOLR behaved with regards to receiving unencoded characters in params (all our requests starting failing). So we had to encode everything sent to the SOLR server. The reason that first URL no longer works is because the param is now getting double encoded. I'll need to add a fix to check for already encoded characters so they don't get double encoded.

**Comment by nickdos** [comment]
Found the issue - most other services are using Grails to obtain the params and Grails unencodes it for us. The download method is directly accessing the `request.queryString` which bypasses any decoding. Fix was to be consistent and use Grails' parameter methods.

**Comment by nickdos** [comment]
I deployed the fix this morning and the encoded version work again.

**Comment by raymondben** [comment]
Yep, all good, many thanks!
