### ISSUE TITLE
Conservation species lists changes

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#130]
Currently using a [JSON config file](https://github.com/AtlasOfLivingAustralia/bie-index/blob/master/grails-app/conf/default-conservation-lists.json) - should be using WS call to lists.ala.org.au and filter on list flags: `isBie` - ideally using `authoritative=true` and `threatened=true` for just conservation lists. 

Issue needs more details and checking for sanity.

**Comment by adam-collins** [comment]
There will be changes to the definition of `label` when moving from relying on https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/bie-index/files/conservation-lists.json to https://lists.ala.org.au/ws/speciesList?isAuthoritative=eq:true&isThreatened=eq:true. Based on existing threatened lists I would use the list `region` as the label, and if absent, the list name abbreviation that appears in brackets at the end of the list name.

**Comment by adam-collins** [comment]
The features built into conservation-lists.json:
- The `uid` supplies the list identifier. 
- The `field` supplies the solr field which will be used to store the conservation status. 
  - Ends up creating really long SOLR field names. e.g. Currently `NSW` will become `New South Wales then used as `conservationStatusNewSouthWales_s`
  - May support multiple conservation lists for a given region, e.g. `conservationStatusNewSouthWales1_s` and `conservationStatusNewSouthWales2_s`. 
  - Incompatible with `ala-bie-hub` `messages.properties`. Might work if changed from `conservationStatusNewSouthWales1_s` to `conservationStatusdr123_s`, that is the encoding of the data resource uid instead of the region into the SOLR field name.
  - Requires changes to `ala-bie-hub` to lookup the species list names. This is probably a good change.
- The `term` supplies the name of the status field. ALA uses the `field` minus the trailing `_s`. This change would be OK.
- `label` gives the label to apply to the conservation status. This is primarily used in the `Refine results` section of `ala-bie-hub` search results page. Meaning the label `Conservation status in Australia` would become `EPBC Act Threatened Species`. This is probably OK to change.
`sourceField` gives the name of the field that contains the conservation status. OK to change.
`kingdomField` gives the name of the field that contains the kingdom -- handy for name lookups, if available. There are a bunch of these. Settling for consistency across conservation-lists is OK to change.

Given the UX/UI review for the BIE this may not be required. 

Changes:
- Add `/indexFields` to openapi. This would be used by `ala-bie-hub` to identify the dynamic conservation fields, `conservationStatus{drUid}`, for use with the `facets` parameter on the search results page.
- Identify conservation lists using the optional search query in the config `lists.conservation`. To make upgrading to dynamic conservation lists more robust this is only used when `conservation-lists.json` has no lists defined. 

Before enabling the use of dynamic conservation status lists, the UI search result and species pages must be updated to deal with the BIE field name changes.
