### ISSUE TITLE
APNI names issue - missing higher taxa

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#131]
Species page for _Gingidia rupicola_:

http://bie.ala.org.au/species/http://id.biodiversity.org.au/name/apni/244542#classification

is missing any higher taxa and thus occurrence records search for the genus don't pickup the species records with this name.

APNI doesn't contain higher taxa - APC has that job.

**Comment by nickdos** [comment]
This issue came up again from FD ticket https://support.ehelp.edu.au/a/tickets/34532.

General consensus was the ALA should be trying to place APNI names, where possible - previously CHAH communicated to the ALA that we were not to do this. This stance looks to have softened and users are demanding that "obvious genus relationships should be linked".

@charvolant has brought this up with Anne (ANBG) and any outcome will be updated here.

**Comment by elywallis** [comment]
If the instruction did originally come from CHAH then Anne (ANBG) won't be able to authorise the change as she's not in CHAH. @charvolant if you need help to go to CHAH for authorisation then just ping me

**Comment by afuchs1** [comment]
Hi Nick

Do you or anyone have a record of the CHAH decision? We have not seen anything.

Anna (APNI/APC editor) and I have been looking at this….

From the APNI/APC perspective, there are 2 scenarios where the name is in APNI but not APC (or any of the equivalents in NSL domains of data – Moss, Fungi etc)

  1.  When a new taxon of the rank of species or below is described with its name parent being an existing APC-accepted genus. In this case the name is not yet placed on the APC tree but logically this is where it is likely to be placed once it has undergone APC consideration. In this scenario, it would be feasible to place this species within the APC-accepted genus (how can we communicate this is an assertion rather than a CHAH decision about the taxonomy?).
  2.  When a taxon of the rank of species or below in for a genus that has not previously been recognised for Australia is recorded for the first time, the genus name will not be in APC. In this scenario the higher taxonomy has not been determined therefore Plantae is about the only feasible option. I am not sure what you should do if the genus is in NZOR?

Niels – do you have an opinion on this?

Cheers, Anne

**Comment by charvolant** [comment]
@elywallis @afuchs Let's just see if that is the CHAH position. I've been checking my emails to and from ABRS from around December 2015 and, while it's indicated in the emails that this is going to happen, not least because there were some fungi greeping into plantae as a result, there's no explicit yes/no from anybody. I remember it being part of the conversation with ABRS about what to do about orphan APNI names and I could possibly see if I can find an old notebook. But it may be that this went through on the nod without anybody really examining it or explicitly taking it up with CHAH.

**Comment by nickdos** [comment]
@elywallis mentioned CHAH involvement, so I'll defer to her :-)

**Comment by nielsklazenga** [comment]
There is no such CHAH decision. This has more likely been an individual CHAH or HISCOM member pretending to speak on behalf of CHAH. We put a stop to that in 2013.

Regarding the classification of taxa in APNI that or not in APC (or any plant taxa that are not in APC), these taxa should get the same classification as their closest ancestor in APC (including this ancestor itself of course), so @afuchs1's first solution, which is what ALA is doing already I think.

**Comment by elywallis** [comment]
@nielsklazenga no, ALA isn't already doing Anne's suggestion which is why this issue comes up. 

I was going to reply to @nickdos and you all to say that the CHAH "directive" was supposedly made before my time and, given the conversation, now appears likely to be either an urban myth or  a point of view pushed by a single person (Niel's contention). 

Either way, I suggest that we should now adopt @afuchs1 suggestion above, and make the change so that a known genus inherits the expected higher taxonomy. The only exception would be a totally novel genus - but even then I would have thought that the paper itself would/ should provide a higher taxonomic placement that could be used?

**Comment by nielsklazenga** [comment]
@elywallis, I do know the history and the "directive" to only use APC came from the NSL, not CHAH. At the time the effect was much worse, as it meant that names of cryptogams (including the ones I care about) weren't matched. Because the mosses are delivered separately now (and are complete), I misinterpreted this issue. I agree with your suggestion.

**Comment by charvolant** [comment]
Looks like it's resolved, then. The next name index will have APNI entries placed according to genus, where possible. This may cause some hiccups when I try to place odd beasts but I'm very happy to do this.

**Comment by elywallis** [comment]
Fabulous, I agree. Thanks @charvolant

**Comment by charvolant** [comment]
Need to resolve multiple synonym-like entries having the same taxonID (eg. name misapplied to multiple other taxa or pro-parte synonym) These tend to come in with a taxonID of the instance, which will be the same for each entry. The acceptedNameID is different in each case, so a composite taxonID is possible.

**Comment by nielsklazenga** [comment]
@charvolant for ALA purposes (a.k.a. name resolution) you should ignore anything that is 'pro parte' or 'misapplied', as they will always lead to incorrect or ambiguous matches. APNI is more a bibliographic system, rather than a taxonomic and/or nomenclatural one, so what APNI sees as fact is someone writing something, or rather some publication using a taxonomic name in a certain way (and then not in a taxonomic concept kind of way, but in an 'as an accepted name', 'as a synonym' etc. kind of way). Of all these different usages, only the heterotypic (taxonomic/subjective) and homotypic (nomenclatural/objective) synonym "usages" are taxonomically useful, the rest is just noise (taxonomically again).

I am a bit of an expert on botanical nomenclature and I couldn't tell you for sure what a pro-parte synonym is. I have asked Brendan and to him it doesn't make sense either, but authors do use it in papers and that's why it is in APNI. Brendan and Anna would want you to ignore all these things. I would say 'then don't deliver it' and it is my understanding that they have been removed from the APC downloads. If you supplement the APC downloads with APNI data, for taxa that are not in APC already, again, best to ignore pro parte synonyms and any misapplications.

@afuchs1 might want to weigh in, hopefully to confirm what I said.

**Comment by charvolant** [comment]
@nielsklazenga We do use things like misapplied names. They act as a data quality flag to indicate a potential problem with the supplied name. Also, if there's a consistent misapplication, then we can refer to the correct name.

There are pro-parte entries in the APC download: `pro parte misapplied`, `pro parte taxonomic synonym`, `pro parte nomenclatural synonym` and variations. We handle any synonym which has multiple accepted taxa badly at the moment, including pro parte. Having said that, my aim, at the very least, is to match onto the least upper bound of all possibilities. Even if we can't decide exactly what sort of parrot something is, at least we can say that it's a bird.

**Comment by afuchs1** [comment]
so talking to Anna, if the mis-applied or pro-parte synonyms only apply to 1 accepted name then they can be applied. If, as the case above indicates, they map to more than 1 accepted name then the best that can be done is to map them to the next highest taxon rank that can be determined. (Until the atlas can deal with levels of uncertainty)

**Comment by charvolant** [comment]
So we handle the 1 accepted name case correctly at the moment. For more than one, it should either give up in shame or move to a higher taxon rank but I don't completely trust it.

**Comment by nielsklazenga** [comment]
I am not exactly sure how they work, as I don't use them, but I would say that, if something is pro-parte, there is always another part and that is the part that is important for name resolution. For example, a name that is a p.p. synonym of another name is also an accepted name, or a proper synonym (or misapplication) of yet another name and the name itself, or the accepted name for the proper synonym is the name that should be matched to. If there is no relationship instance for a name other than the pro-parte relationship instance(s), you have to assume that the name itself is accepted, so that should be the matched name. In any case, all 'pro-parte' relationships should be ignored, no matter if there are one or more per name. They are always misleading and will always result in an incorrect match.

Leaving out the 'pro-parte' relationship instances should remove all duplication from APC and reduce the duplication in APNI to conflicts between treatments. These cannot be resolved algorithmically (so I would just match/resolve those names to themselves). In the case of misapplications it can also be a matter of geographical scope.

We can agree to disagree on the misapplied names. At the occurrence level misapplied names are, by definition, misidentifications, so, as long as there is a data quality assertion, it doesn't really matter what name they are matched to.

@charvolant, you will love the RCC-5 relationships we are putting in the new standard. That should make some of these things nice and clear.

**Comment by ansell** [comment]
I can see the higher taxa above the species that was referenced in the OP, so closing this as fixed.
