### ISSUE TITLE
Missing higher taxa for Moss genus

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#134]
`Wijkia` - http://bie.ala.org.au/species/e851274b-d043-4cef-ba01-2a7eb5abc80f and http://bie.ala.org.au/ws/species/e851274b-d043-4cef-ba01-2a7eb5abc80f

Reported here: https://github.com/AtlasOfLivingAustralia/ALA4R/issues/24

**Comment by charvolant** [comment]
Potentially caused by load order of datasets, with AusMoss hooking into the APC dataset at higher levels. if AusMoss is loaded first in the bie-index, then the single load will be unable to denormalise the higher taxa. When I load the new set into bie-index, I'll check it and see if it's correctly denormalised.

**Comment by adam-collins** [comment]
No longer relevant.
