### ISSUE TITLE
Genus search showing NZOR higher than APC

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#166]
http://bie.ala.org.au/search?q=Dianella

The APC result should be the first result not second. NZOR version should also be a pointer to APC version but has extra `ex Juss.` text that is probably confusing names parser.

The issue is with biocache searches, as the NZOR name is being used over the APC when doing a name search.

http://biocache.ala.org.au/occurrences/search?taxa=Dianella

128 results are for NZOR version.

**Comment by charvolant** [comment]
Dianella Lam. ex Juss. (NZOR) should be treated as having the same author as Dianella Lam. (APNI) since  the "ex Juss." means that Jussieu validly published a previous name. Unfortunately, the zoological convention puts the situation in reverse. eg. "Walbaum (ex Klein), 1792"

Author comparison is done by the GBIF libraries but it generally works only at the abbreviation level. This may require more sophisticated parsing. gnparser https://github.com/GlobalNamesArchitecture/gnparser identifies the ex Juss. part but not (ex Klien), 1972
