### ISSUE TITLE
Strange search results

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#196]
https://bie.ala.org.au/ws/search.json?q=scientificName_s:%22Acacia+dealbata%22

https://bie.ala.org.au/ws/search.json?q=rk_species:%22Acacia+dealbata%22

https://bie.ala.org.au/ws/search.json?q=nameID:%22Acacia+dealbata%22

https://bie.ala.org.au/ws/search.json?q=scientificName_s:%22Charopidae%20species%20100%20M.37918%22

all give the same 529 results.

Also https://bie.ala.org.au/ws/search.json?q=%22Acacia+dealbata%22

should only return 1 hit (maybe 2) but is instead returning 4043 hits and is the same as https://bie.ala.org.au/ws/search.json?q=Acacia+OR+dealbata, suggesting the quotes are being stripped out somewhere.

**Comment by adam-collins** [comment]
Appears resolved. Different counts are returned for each today.

**Comment by adam-collins** [comment]
Reopened because while fixing https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/107 I noticed it was doing a fuzzy search and that the interpretation of a query was not as straight forward as I had thought.

Applying a fix to skip interpretation when:
- A field is specified in the search, e.g. field:value. The reason for this is that the interpretation is currently converting this to the form  `field:value OR field OR value`
- The q value is a quoted string, e.g. "Sagittaria platyphylla". The reason for this is that this issue identifies that quoted searches should perform as described rather than the form `"Sagittaria platyphylla" OR Sagittaria OR platyphylla`

Adding recognition of `\h` spaces when splitting terms during interpretation because of https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/107

Extending character definition so that latin characters are no longer removed when constructing the fuzzy search.

Pull request https://github.com/AtlasOfLivingAustralia/bie-index/pull/380
