### ISSUE TITLE
Add ranking of image sources at index time

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/bie-index#3]
Add a configurable list of image sources that will be given preference at index time.
This list should be configurable in the admin console or just via external config

**Comment by charvolant** [comment]
A couple of notes:

* As a basic start, a list of data sources that give a boost to image choice.
* The current bie divides images into type images, specimen images and images. Specimen images and types images may not be the best thing to use, since they're usually dead things.
* Add a facility to allow a specific image to be used as the core image for the species, so that we choose a "good" image for display. This can be done via a simple administrative interface in bie-index, with the update going into the bie solr index

**Comment by ansell** [comment]
In terms of the preferred image, the MDBA have a list of images that they prefer for a small number of their iconic species, which would be ideal if it could be managed by another server rather than mdba-hub because mdba-hub doesn't currently have a database and is still a fairly thin-hub. 

Ping @sat01a who is working on the mdba species images at:

https://github.com/AtlasOfLivingAustralia/mdba-hub/issues/48

**Comment by charvolant** [comment]
Current image loading is to build a gigantic list of potential images during a DwCA load. One is then picked, by the simple process of happening to be the last one against that name, to act as the image. This is done by name matching.

Suggested new process is to post-load images, so that we can match them against proper taxonIDs rather than relying on name matches, which are a bit of a problem for the bie-index.

The bie-index tends to blow away data when new data is loaded, so while its possible to keep documents in it and copy them across when building a new index, things should probably come from somewhere a little bit more permanent. A species list, a-la https://github.com/AtlasOfLivingAustralia/mdba-hub/issues/48 looks a bit of a better bet.

So the process would be:

1. Build a new bie-index index and ala-name-matching index with various DwCAs
2. Run the new namematching index across the biocache and collectory name lists to match supplied names against possibly new taxonIDs
3. Update the bie-index index with matched images. This basically means loading lists of preferred images and, for those that don't have a specific preferred image, searching the biocache with boosts set for a good datasetID

**Comment by adam-collins** [comment]
If I understand correctly this is referring to occurrence sources and the requirement to add preference to particular data resources when updating the image assigned in the index.

This appears to be supported through the `default-image-lists.json` file using the `preferred` array. Add to this array the `fq` statements required to return only the preferred dataResources. If no image is found then this `preferred` array excluded and another search executed only with `default-image-lists.json` file's `required` array.
