### ISSUE TITLE
Conservation statuses are incorrect for some taxa

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/bie-index#388]
See slack chat for full reporting of issue:
https://atlaslivingaustralia.slack.com/archives/C03EJ7ARZQW/p1714953826065419

Conservation statuses are incorrect for some taxa. It appears that in some cases they are populating from a higher taxonomic rank. 

Issues reported:
- Eucalyptus populnea is not listed, but is picking up statuses from Eucalytpus (https://bie.ala.org.au/species/https%3A//id.biodiversity.org.au/taxon/apni/51738743#overview) (Critically Endangered Vic and Priority 1 WA) and also for Myrtaceae (Qld Vunerable and WA Priority 4: Near Threatened).
Eucalyptus and Myrtaceae are picking up those statuses from threatened species that have been synonymised to those taxon ranks.

- Eucalyptus is being listed as both CE and E in Victoria because there are two hybrid entries that are being matched to genus https://lists.ala.org.au/speciesListItem/list/dr655?q=eucalyptus+x

- this species group API (called by explore your area but in other places as well) is generating incorrect (embarrassing) data:
[https://biocache.ala.org.au/download?searchParams=%3Fq%3D*%3A*%26lat%3D-26.5711%26lon%[…]%26fq%3Dspecies_group%3APlants&targetUri=/explore/your-area](https://biocache.ala.org.au/download?searchParams=%3Fq%3D*%3A*%26lat%3D-26.5711%26lon%3D148.7857%26radius%3D5%26fq%3DspatiallyValid%3Atrue%26fq%3Dspecies_group%3APlants&targetUri=/explore/your-area)
        - conservation statuses are just plain incorrect
        - whether the last 3 lists should be included is questionable (WoNS, WA Pests, VIC Pests)

- the download species checklist from Biocache returns the same errors too.

**Comment by adam-collins** [comment]
bie-index is behaving correctly. If a species list matches a genus, then this is what pipelines, biocache and bie-index will use. 

When an authoritative species list is uploaded, matches are manually corrected. I suspect these were missed when last checked. 

Regarding the inclusion of WoNS, WA Pests, VIC Pests in species list downloads; 
1. Add a new flag to lists so that these can be distinguished from other authoritative and invasive lists.
2. Or, remove the invasive list flag in lists for WoNS, WA Pests, VIC Pests.
3. Or, make a new github issue in biocache-service for the removal authoritative & invasive list information from downloaded species lists.

**Comment by Sherrin-ALA** [comment]
When a species is being added to a checklist, it appears that the threatened status of any parent taxon (genus or family) is getting assigned to the species. For example: _Eucalyptus camaldulensis_ is not listed in Victoria, but is listed as "Critically Endangered" in Victoria for checklists downloaded from "find my area" because Eucalyptus (incorrectly) has a status of critically endangered.

This issue was discussed in the taxonomic working group yesterday, and the consensus was that for these checklists:
Species shouldn't be inheriting threatened status from higher taxonomy above the level of species (at genus or higher).
Unlisted subspecies, however, should inherit threatened status from their parent species

**Comment by adam-collins** [comment]
Moving this issue to the appropriate dependency https://github.com/AtlasOfLivingAustralia/species-lists/issues/96
