### ISSUE TITLE
SOLR search results missing acceptedConceptName

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#95]
When searching for a name in SOLR, the results doc will contain the fields  `acceptedConceptName` and `acceptedConceptID`, except when the name itself is has `taxonomicStatus: "accepted"` - in which case, those fields are not populated. This is reflected in some services where we see:

```
{  
  Acacia cyperophylla:[  
    {  
      identifier:"http://id.biodiversity.org.au/node/apni/2920327",
      name:"Acacia cyperophylla",
      acceptedIdentifier:"http://id.biodiversity.org.au/node/apni/2920327",
      acceptedName:null
    },
    {  
      identifier:"http://id.biodiversity.org.au/instance/apni/848849",
      name:"Acacia cyperophylla",
      acceptedIdentifier:"http://id.biodiversity.org.au/node/apni/2905602",
      acceptedName:"Acacia sibina Maslin"
    }
  ]
}
```

I think we should explicitly say the `acceptedConceptName`  and `acceptedConceptID` and not assume from another field.

**Comment by charvolant** [comment]
There are quite a few code paths that determine whether something is a synonym by whether there is an acceptedConceptID or not. This is partially because there's a wide variety of taxonomic status terms that mean 'synonym' in various ways. So we'll need to do a code audit (and we should include an isSynonym method) to catch them all.

**Comment by nickdos** [comment]
fixed but needs testing

**Comment by adam-collins** [comment]
testing must have have been done by now
